name: $(BuildID)
trigger: none
pr: none
schedules:
- cron: "0 17 * * 2"
  displayName: Weekly Tuesday release
  branches:
    include:
    - master
  always: true
parameters:
- name: dry_run
  type: boolean
  default: false


stages:
- stage: create
  displayName: Create release
  jobs:
  - template: jobs/release/create-release-commits.yml

- stage: build
  displayName: Build docs and wheels
  jobs:
  - template: jobs/release/build-wheels.yml
  - template: jobs/release/build-api-docs.yml
  dependsOn:
  - create

- stage: verify
  displayName: Verify wheels
  jobs:
  - template: jobs/release/verify.yml
  dependsOn:
  - build

- stage: publish
  displayName: Publish release
  jobs:
  - template: jobs/release/publish-release-commits.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}
  - template: jobs/release/publish-api-docs.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}
  - template: jobs/release/publish-pypi.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}
  dependsOn:
  - verify
