parameters:
- name: pools
  type: object
  default: [ "ubuntu-20.04", "windows-2022", "macos-11" ]

jobs:
- ${{ each pool in parameters.pools }}:
  - job:
    displayName: Build wheels on ${{ pool }}
    pool:
      vmImage: ${{ pool }}
    ${{ if contains(pool, 'ubuntu') }}:
      container:
        image: quay.io/pypa/manylinux2010_x86_64
    steps:
    - template: setup-host.yml
      ${{ if contains(pool, 'ubuntu') }}:
        parameters:
          python: /opt/python/cp36-cp36m/bin/python

    - task: DownloadPipelineArtifact@2
      displayName: Download artifact ${{ parameters.artifact }}
      inputs:
        artifactName: sdist
        targetPath: sdist

    - bash: scripts/build_wheels.sh $(python) sdist
      displayName: Build wheels

    - task: PublishPipelineArtifact@1
      displayName: Publish wheel artifact
      inputs:
        artifactName: wheels-${{ pool }}
        targetPath: wheels

    - script: $(python) -m pip install twine

    - script: $(python) -m twine check wheels/*
      displayName: Check artifacts are valid for PyPI
