parameters:
- name: pools
  type: object
  default: [ "ubuntu-22.04", "windows-2022", "macos-11" ]

jobs:
- ${{ each pool in parameters.pools }}:
  - job:
    displayName: Build wheels on ${{ pool }}
    pool:
      vmImage: ${{ pool }}
    steps:
    - template: setup-host.yml
    - task: DownloadPipelineArtifact@2
      displayName: Download artifact ${{ parameters.artifact }}
      inputs:
        artifactName: sdist
        targetPath: sdist

    - bash: scripts/build_wheels.sh sdist
      displayName: Build wheels

    - task: PublishPipelineArtifact@1
      displayName: Publish wheel artifact
      inputs:
        artifactName: wheels-${{ pool }}
        targetPath: wheels

    - script: python -m pip install twine
      displayName: Install twine

    - script: python -m twine check wheels/*
      displayName: Check artifacts are valid for PyPI
