jobs:
- job:
  displayName: Create release tags
  pool:
    vmImage: ubuntu-22.04
  steps:
  - template: setup-host.yml
    parameters:
      git: true

  - bash: scripts/create_repos.sh
    displayName: Checkout all repos

  - bash: scripts/create_release_commits.sh
    displayName: Create release commits

  - task: PublishPipelineArtifact@1
    displayName: Publish repos artifact
    inputs:
      artifactName: repos
      targetPath: repos

  - bash: scripts/create_release_artifact.sh
    displayName: Create release artifact

  - task: PublishPipelineArtifact@1
    displayName: Publish release.yml
    inputs:
      artifactName: release.yml
      targetPath: release.yml

  - bash: scripts/create_sdist.sh
    displayName: Create sdists

  - task: PublishPipelineArtifact@1
    displayName: Publish sdist pacakges
    inputs:
      artifactName: sdist
      targetPath: sdist

  - script: pip install twine

  - script: twine check sdist/*
    displayName: Check artifacts are valid for PyPI
