parameters:
- name: dry_run
  type: boolean
  default: true

jobs:
- job:
  displayName: Publish release commits
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml
    parameters:
      git: true

  - task: DownloadPipelineArtifact@2
    displayName: Download repos
    inputs:
      artifactName: repos
      targetPath: repos

  - bash: scripts/publish_release_commits.sh
    displayName: Publish release commits
    env:
      DRY_RUN: ${{ lower(parameters.dry_run) }}

  - bash: scripts/bump_versions.sh
    displayName: Bump versions on master
    env:
      DRY_RUN: ${{ lower(parameters.dry_run) }}
      GH_TOKEN: $(GH_TOKEN)
