parameters:
- name: pools
  type: object
  default: [ "ubuntu-20.04", "windows-2022", "macos-11" ]

jobs:
- ${{ each pool in parameters.pools }}:
  - job:
    displayName: Verify on ${{ pool }}
    pool:
      vmImage: ${{ pool }}
    steps:
    - template: setup-host.yml
    - template: setup-venv-from-artifact.yml
      parameters:
        artifact: wheels-${{ pool }}

    - bash: |
        source angr_venv/bin/activate &> /dev/null || source angr_venv/Scripts/activate
        python -c "import angr; print('angr imports!')"
      displayName: Test angr import
