parameters:
- name: pools
  type: object
  default: [ "ubuntu-22.04", "windows-2022", "macos-11" ]

jobs:
- ${{ each pool in parameters.pools }}:
  - job:
    displayName: Verify on ${{ pool }}
    pool:
      vmImage: ${{ pool }}
    steps:
    - template: setup-host.yml

    - task: DownloadPipelineArtifact@2
      displayName: Download artifact wheels-${{ pool }}
      inputs:
        artifactName: wheels-${{ pool }}
        targetPath: wheels-${{ pool }}

    - task: DownloadPipelineArtifact@2
      displayName: Download artifact wheels-${{ pool }}
      condition: not(eq('${{ pool }}', 'ubuntu-22.04'))
      inputs:
        artifactName: wheels-ubuntu-22.04
        targetPath: wheels-ubuntu-22.04

    - bash: |
        python -m venv angr_venv
        source angr_venv/bin/activate &> /dev/null || source angr_venv/Scripts/activate
        export PIP_FIND_LINKS="wheels-${{ pool }} wheels-ubuntu-22.04"
        pip install wheels-${{ pool }}/*.whl
      displayName: Test wheel install

    - bash: |
        source angr_venv/bin/activate &> /dev/null || source angr_venv/Scripts/activate
        python -c "import angr; print('angr imports!')"
      displayName: Test angr import
