name: angr CI

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: angr/ci:2
    steps:
    - run: /root/scripts/azure-build.sh
      name: Build CI artifact
    - uses: actions/upload-artifact@v3
      with:
        name: build_archive
        path: ./build.tar.gz

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    container:
      image: angr/ci:2
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build_archive
    - run: /root/scripts/azure-lint.sh
      name: Run linter


  test:
    name: Test
    runs-on: ubuntu-20.04
    container:
      image: angr/ci:2
    needs: build
    strategy:
      fail-fast: false
      matrix:
        worker: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build_archive
    - run: /root/scripts/azure-test.sh
      name: Run tests
      env:
        WORKER: ${{ matrix.worker }}
        NUM_WORKERS: 10

