name: angr CI

on:
  workflow_call:
    inputs:
      nightly:
        description: "Enable nightly-only tests"
        default: false
        type: boolean
        required: false
      container_image:
        description: "Container image to use"
        default: "angr/ci:3"
        type: string
        required: false
      afl:
        description: "Set AFL parameters during test stage"
        default: false
        type: boolean
        required: false
      include_self:
        description: "Include self in the test stage"
        default: true
        type: boolean
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.container_image }}
    steps:
    - run: /root/scripts/ga-build.sh
      name: Build CI artifact
      id: main
      env:
        NIGHTLY: ${{ inputs.nightly }}
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: build_archive
        path: ./build.tar.zst
        compression-level: 0
    outputs:
      snapshot_branch: ${{ steps.main.outputs.snapshot_branch }}

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.container_image }}
    needs: build
    steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: build_archive
    - run: /root/scripts/ga-lint.sh
      name: Run linter

  typecheck:
    name: Typecheck
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.container_image }}
    needs: build
    steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: build_archive
    - run: /root/scripts/ga-typecheck.sh
      name: Run type checker

  test:
    name: Test
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.container_image }}
      options: -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc --cap-add=SYS_PTRACE --security-opt seccomp:unconfined
    needs: build
    strategy:
      fail-fast: false
      matrix:
        worker: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
    - run: |
        echo 1 | tee /hostproc/sys/kernel/sched_child_runs_first
        echo core | tee /hostproc/sys/kernel/core_pattern
      name: Set AFL parameters
      if: ${{ inputs.afl }}
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: build_archive
    - run: /root/scripts/ga-test.sh
      name: Run tests
      env:
        WORKER: ${{ matrix.worker }}
        NUM_WORKERS: 10
        INCLUDE_SELF: ${{ inputs.include_self }}
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: always()
      with:
        name: Test Results ${{ matrix.worker }}
        path: build/results/*.tests.xml

  corpus-test:
    name: Decompiler Snapshot Testing
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.container_image }}
    needs: build
    strategy:
      matrix:
        worker: [0]  # could be expanded when we increase the workload
    steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: build_archive
    - run: /root/scripts/ga-corpustest.sh
      name: Run tests
      env:
        WORKER: ${{ matrix.worker }}
        NUM_WORKERS: 1
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: always()
      with:
        name: corpus_diffs
        path: build/results/*.diff

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs:
    - build
    - test
    - corpus-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send result email
        if: inputs.nightly && needs.test.result == 'failure'
        env:
          MAILGUN_API_TOKEN: ${{ secrets.MAILGUN_API_TOKEN }}
        run: |
          BUILD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -s --user "api:$MAILGUN_API_TOKEN" \
            https://api.mailgun.net/v3/mail.rev.fish/messages \
            -F from="angr Nightly CI <angr-nightly-ci@mail.rev.fish>" \
            -F to=angr-dev@asu.edu \
            -F subject="$GITHUB_REPOSITORY nightly CI failed" \
            -F text="Link to failed run: $BUILD_URL"

      - name: Trigger corpus upload
        if: needs.build.result == 'success' && needs.corpus-test.result == 'success' && vars.SNAPSHOTS_DISPATCH_TOKEN != ''
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: "angr-corpus-upload.yml"
          repo: angr/snapshots-deputy
          token: ${{ vars.SNAPSHOTS_DISPATCH_TOKEN }}
          ref: main
          inputs: |
            {
              "run_id": "${{ github.run_id }}",
              "source_repository": "${{ github.event.repository.name }}",
              "source_commit": "${{ github.sha }}",
              "target_branch": "${{ needs.build.outputs.snapshot_branch }}",
              "pull_request": "${{ github.event.number }}"
            }
